baseURL = "https://shenguojun.github.io/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en-us"
title = "Lawrence's Blog"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
hasCJKLanguage = true

[Params]
  subtitle = "臨淵羡魚，不如退而結網"
  logo = "lawrencesgj.jpg"
  favicon = "lawrencesgj.jpg"
  commit = false
  rss = true
  comments = true

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3


[Author]
  name = "申国骏"
  email = "junguoshen@yeah.net"
  github = "shenguojun"
  linkedin = "guojunshen"
